# Generated by Django 4.0.4 on 2022-04-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': 'resumes'},
        ),
    ]
